In [1]:
import tensorflow as tf
import tensorflow_datasets as tfds
num_epoch=5
batch_size=19
learning_rate=0.001
dataset=tfds.load('tf_flowers',split=tfds.Split.TRAIN,as_supervised=True)
dataset=dataset.map(lambda img,label:(tf.image.resize(img,(224,224))/255.0,label)).shuffle(1024).batch(batch_size)

In [6]:
model=tf.keras.applications.MobileNetV2(weights=None,classes=5)
optimizer=tf.keras.optimizers.Adam(learning_rate=learning_rate)
for images,labels in dataset:
    with tf.GradientTape() as tape:
        labels_pred=model(images,training=True)
        loss=tf.keras.losses.sparse_categorical_crossentropy(y_true=labels,y_pred=labels_pred)
    grads=tape.gradient(loss,model.trainable_variables)
    break

In [7]:
loss

<tf.Tensor: shape=(19,), dtype=float32, numpy=
array([2.354484  , 0.7426211 , 2.360015  , 2.5043774 , 0.6109825 ,
       1.3381376 , 1.9226781 , 0.929811  , 0.5746781 , 2.0790977 ,
       1.9812402 , 0.8664483 , 0.77585876, 2.3482049 , 0.74476457,
       1.8137462 , 2.0364108 , 1.9775335 , 0.82613796], dtype=float32)>

In [8]:
grads

[<tf.Tensor: shape=(3, 3, 3, 32), dtype=float32, numpy=
 array([[[[-2.77149067e+01,  1.13518066e+01,  8.30960655e+00,
           -2.25895958e+01,  3.68642569e+00, -6.23381090e+00,
           -2.48839140e+00,  1.36041088e+01, -1.62768898e+01,
           -5.82029772e+00,  5.22809601e+00, -4.71891451e+00,
           -1.95325792e-01,  6.58166218e+00,  1.72617874e+01,
            2.97917295e+00,  4.10811901e+00,  2.57341099e+01,
           -2.87806664e+01, -1.09675646e+01,  6.22786856e+00,
            2.84537334e+01,  4.52938700e+00, -1.67781715e+01,
            1.93367577e+01, -1.79429799e-01, -6.48499310e-01,
            3.93829498e+01,  2.88528595e+01, -1.29376221e+01,
            1.05176439e+01, -3.83543968e+01],
          [-1.50287113e+01,  3.41833735e+00,  3.16507697e+00,
           -3.38876305e+01,  6.68931723e+00, -8.21777153e+00,
           -4.53400517e+00,  4.61951494e+00, -1.55527401e+01,
           -6.82030964e+00,  3.51185131e+00,  1.07792625e+01,
           -4.00427103e-01,  1